Created home page and started individual photo page
redliz5808/AThousandWords pull request #1
Opened 2021-04-22 21:14 UTC by redliz5808

2021-04-23 11:58 UTC, yoloOnTheBattlefield requested changes

2021-04-23 11:58 UTC, yoloOnTheBattlefield commented on src/pages/Home/index.js
> +            Object.entries(this.state.data).map((entry) => {
You can use Objec.values here :D

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/values

2021-04-23 11:58 UTC, yoloOnTheBattlefield commented on src/pages/Photo/index.js
> +      console.log(data);
no console

2021-04-26 07:36 UTC, yoloOnTheBattlefield requested changes

2021-04-26 07:36 UTC, yoloOnTheBattlefield commented on src/App.js
> +          <Route component={(props) => <Home {...props} />} exact path="/"></Route>
why not ` <Route component={Home} exact path="/" />`? you are not passing anything to Home

2021-04-26 07:36 UTC, yoloOnTheBattlefield commented on src/pages/Home/Home.js
> +      this.setState({ page: button });
button will come in as a string, you might have to convert it to number

2021-04-26 07:36 UTC, yoloOnTheBattlefield commented on src/pages/Home/Home.js
> +                console.log(value);
😅😅😅

2021-04-26 16:34 UTC, reekArd approved these changes

2021-04-26 16:47 UTC, merged